build:
  version: 4.0

cards:
  message: "welcome to eazybank cards related local apis"
  type: "cards"
  contactDetails:
    name: "john Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555)555-1234
    - (555)555-1235