build:
  version: 1.0

cards:
  message: "welcome to eazybank cards related prod apis"
  type: "cards"
  contactDetails:
    name: "D Roy - Release Manager"
    email: "Droy@eazybank.com"
  onCallSupport:
    - (777)555-1236
    - (777)555-1237