build:
  version: 4.0

accounts:
  message: "welcome to eazybank account related local apis"
  contactDetails:
    name: "john Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
      - (555)555-1234
      - (555)555-1235