build:
  version: 3.0

cards:
  message: "welcome to eazybank cards related QA apis"
  type: "cards"
  contactDetails:
    name: "smitha Roy - QA Lead"
    email: "smitha@eazybank.com"
  onCallSupport:
    - (666)555-1236
    - (666)555-1237